on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Lint
        run: cd backend/ && npm run lint

      - name: Check formatting
        run: cd backend/ && npm run prettier-check

  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Build
        run: cd backend/ && npm run build
        
      - name: Print PG_CREDENTIALS
        run: echo "$PG_CREDENTIALS"

  test:
    runs-on: ubuntu-latest
    name: Test Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Build Docker image
        run: |
          docker build -t eatr-db ./
        working-directory: ./backend

      - name: Run and Start Docker container
        run: |
          docker run -d --name eatr-container -p 5432:5432 eatr-db
          docker start eatr-container

      - name: Build and test
        env:
          #PG_HOST: 0.0.0.0
          #PG_USERNAME: postgres
          #PG_PASSWORD: Eatr123!
          #PG_DATABASE: eatr
          #PG_PORT: 5432
          PG_CREDENTIALS: '{"host":"0.0.0.0","port":"5432","username":"postgres","password":"Eatr123!"}'
          PG_SSLDISABLE: 1
        run: |
          cd backend
          npm test
