on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run prettier-check
