on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Lint
        run: cd backend/ && npm run lint

      - name: Check formatting
        run: cd backend/ && npm run prettier-check

  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

     - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Build
        run: cd backend/ && npm run build 

  test: 
    runs-on: ubuntu-latest
    name: Build Project
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

     - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM packages
        run: cd backend/ && npm install

      - name: Test
        run: cd backend/ && npm run test